"""nuevas_tablas

Revision ID: 27336de86ea7
Revises: d483882f2a11
Create Date: 2023-08-01 23:41:40.514469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27336de86ea7'
down_revision = 'd483882f2a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clave', sa.String(length=100), nullable=False))
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('clave')

    # ### end Alembic commands ###
