"""Crear post comentario y categoria

Revision ID: 6fce10ad8776
Revises: 9a53a143a17f
Create Date: 2023-08-01 20:28:46.223858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fce10ad8776'
down_revision = '9a53a143a17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto_comentario', sa.String(length=500), nullable=False),
    sa.Column('fecha_creacion', sa.String(length=100), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contraseña', sa.String(length=100), nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('clave')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clave', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('contraseña')
        batch_op.drop_column('correo')

    op.drop_table('comentario')
    op.drop_table('post')
    op.drop_table('categoria')
    # ### end Alembic commands ###
